# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hi
email: devbiji@gmail.com
description: /home/biji
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://biji1.github.io" # the base hostname & protocol for your site
youtube_username: UberBiji
twitter_username: UberBiji
github_username: biji1
paginate: 3

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
